{"name": "test_login_bemsucedido", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'find_element'", "trace": "fixturefunc = <function inserir_credenciais at 0x0000023F34AAC9A0>\nrequest = <FixtureRequest for <Function test_login_bemsucedido>>\nkwargs = {'login_page': <pages.login_page.LoginPage object at 0x0000023F34AB2650>}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\nC:\\Users\\isabela.romanini\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py:898: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests\\test_login.py:33: in inserir_credenciais\n    login_page.login(\"testeisabelaromanini@teste.com\", \"Test@2123\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.login_page.LoginPage object at 0x0000023F34AB2650>\nusername = 'testeisabelaromanini@teste.com', password = 'Test@2123'\n\n    def login(self, username, password):\n        \"\"\"Realiza o login preenchendo os campos e clicando no botÃ£o.\"\"\"\n>       self.driver.find_element(*self.username_input).send_keys(username)\nE       AttributeError: 'NoneType' object has no attribute 'find_element'\n\npages\\login_page.py:19: AttributeError"}, "description": "../features/test_login.feature: Login bem-sucedido", "start": 1741010046091, "stop": 1741010050340, "uuid": "722a22fd-13a8-4c8a-b65f-fe141c2a4a8d", "historyId": "f7ac102bbb6279eeeefe88f91dcebd43", "testCaseId": "f7ac102bbb6279eeeefe88f91dcebd43", "fullName": "tests.test_login#test_login_bemsucedido", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PWIROMANINI"}, {"name": "thread", "value": "28408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}